package com.kira.kdownloader.settings;

import java.util.Objects;

public final class BehaviorSettings {
    private final boolean confirmBeforeDownload; private final int maxSimultaneousDownloads,maxRetryCount;
    private final boolean autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates;
    private final DuplicateDetection duplicateDetection; private final QueuePosition newDownloadPosition;
    private final boolean keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled;
    private final int speedLimitKbps; private final boolean scheduleEnabled; private final int scheduleStartMinutes,scheduleEndMinutes;
    private final PostDownloadAction postDownloadAction;
    public BehaviorSettings(){this(false,2,3,true,true,true,DuplicateDetection.SOURCE_URL,QueuePosition.BOTTOM,false,true,true,true,false,1024,false,0,360,PostDownloadAction.NOTHING);}
    public BehaviorSettings(boolean confirmBeforeDownload,int maxSimultaneousDownloads,int maxRetryCount,boolean autoResumeInterrupted,
                            boolean resumeQueueAfterRestart,boolean preventDuplicates,DuplicateDetection duplicateDetection,
                            QueuePosition newDownloadPosition,boolean keepScreenAwake,boolean pauseOnBatterySaver,boolean pauseOnOverheat,
                            boolean autoRetryOnReconnect,boolean speedLimitEnabled,int speedLimitKbps,boolean scheduleEnabled,
                            int scheduleStartMinutes,int scheduleEndMinutes,PostDownloadAction postDownloadAction){this.confirmBeforeDownload=confirmBeforeDownload;this.maxSimultaneousDownloads=maxSimultaneousDownloads;this.maxRetryCount=maxRetryCount;this.autoResumeInterrupted=autoResumeInterrupted;this.resumeQueueAfterRestart=resumeQueueAfterRestart;this.preventDuplicates=preventDuplicates;this.duplicateDetection=duplicateDetection;this.newDownloadPosition=newDownloadPosition;this.keepScreenAwake=keepScreenAwake;this.pauseOnBatterySaver=pauseOnBatterySaver;this.pauseOnOverheat=pauseOnOverheat;this.autoRetryOnReconnect=autoRetryOnReconnect;this.speedLimitEnabled=speedLimitEnabled;this.speedLimitKbps=speedLimitKbps;this.scheduleEnabled=scheduleEnabled;this.scheduleStartMinutes=scheduleStartMinutes;this.scheduleEndMinutes=scheduleEndMinutes;this.postDownloadAction=postDownloadAction;}
    public boolean getConfirmBeforeDownload(){return confirmBeforeDownload;} public int getMaxSimultaneousDownloads(){return maxSimultaneousDownloads;}
    public int getMaxRetryCount(){return maxRetryCount;} public boolean getAutoResumeInterrupted(){return autoResumeInterrupted;}
    public boolean getResumeQueueAfterRestart(){return resumeQueueAfterRestart;} public boolean getPreventDuplicates(){return preventDuplicates;}
    public DuplicateDetection getDuplicateDetection(){return duplicateDetection;} public QueuePosition getNewDownloadPosition(){return newDownloadPosition;}
    public boolean getKeepScreenAwake(){return keepScreenAwake;} public boolean getPauseOnBatterySaver(){return pauseOnBatterySaver;}
    public boolean getPauseOnOverheat(){return pauseOnOverheat;} public boolean getAutoRetryOnReconnect(){return autoRetryOnReconnect;}
    public boolean getSpeedLimitEnabled(){return speedLimitEnabled;} public int getSpeedLimitKbps(){return speedLimitKbps;}
    public boolean getScheduleEnabled(){return scheduleEnabled;} public int getScheduleStartMinutes(){return scheduleStartMinutes;}
    public int getScheduleEndMinutes(){return scheduleEndMinutes;} public PostDownloadAction getPostDownloadAction(){return postDownloadAction;}
    public BehaviorSettings withConfirmBeforeDownload(boolean v){return build(v,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withMaxSimultaneousDownloads(int v){return build(confirmBeforeDownload,v,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withMaxRetryCount(int v){return build(confirmBeforeDownload,maxSimultaneousDownloads,v,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withAutoResumeInterrupted(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,v,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withResumeQueueAfterRestart(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,v,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withPreventDuplicates(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,v,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withDuplicateDetection(DuplicateDetection v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,v,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withNewDownloadPosition(QueuePosition v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,v,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withKeepScreenAwake(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,v,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withPauseOnBatterySaver(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,v,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withPauseOnOverheat(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,v,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withAutoRetryOnReconnect(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,v,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withSpeedLimitEnabled(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,v,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withSpeedLimitKbps(int v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,v,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withScheduleEnabled(boolean v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,v,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withScheduleStartMinutes(int v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,v,scheduleEndMinutes,postDownloadAction);}
    public BehaviorSettings withScheduleEndMinutes(int v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,v,postDownloadAction);}
    public BehaviorSettings withPostDownloadAction(PostDownloadAction v){return build(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,v);}
    private static BehaviorSettings build(boolean a,int b,int c,boolean d,boolean e,boolean f,DuplicateDetection g,QueuePosition h,boolean i,boolean j,boolean k,boolean l,boolean m,int n,boolean o,int p,int q,PostDownloadAction r){return new BehaviorSettings(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r);}
    @Override public boolean equals(Object o){if(this==o)return true;if(!(o instanceof BehaviorSettings))return false;BehaviorSettings x=(BehaviorSettings)o;return confirmBeforeDownload==x.confirmBeforeDownload&&maxSimultaneousDownloads==x.maxSimultaneousDownloads&&maxRetryCount==x.maxRetryCount&&autoResumeInterrupted==x.autoResumeInterrupted&&resumeQueueAfterRestart==x.resumeQueueAfterRestart&&preventDuplicates==x.preventDuplicates&&keepScreenAwake==x.keepScreenAwake&&pauseOnBatterySaver==x.pauseOnBatterySaver&&pauseOnOverheat==x.pauseOnOverheat&&autoRetryOnReconnect==x.autoRetryOnReconnect&&speedLimitEnabled==x.speedLimitEnabled&&speedLimitKbps==x.speedLimitKbps&&scheduleEnabled==x.scheduleEnabled&&scheduleStartMinutes==x.scheduleStartMinutes&&scheduleEndMinutes==x.scheduleEndMinutes&&duplicateDetection==x.duplicateDetection&&newDownloadPosition==x.newDownloadPosition&&postDownloadAction==x.postDownloadAction;}
    @Override public int hashCode(){return Objects.hash(confirmBeforeDownload,maxSimultaneousDownloads,maxRetryCount,autoResumeInterrupted,resumeQueueAfterRestart,preventDuplicates,duplicateDetection,newDownloadPosition,keepScreenAwake,pauseOnBatterySaver,pauseOnOverheat,autoRetryOnReconnect,speedLimitEnabled,speedLimitKbps,scheduleEnabled,scheduleStartMinutes,scheduleEndMinutes,postDownloadAction);}
    @Override public String toString(){return "BehaviorSettings(confirmBeforeDownload="+confirmBeforeDownload+", maxSimultaneousDownloads="+maxSimultaneousDownloads+", maxRetryCount="+maxRetryCount+", autoResumeInterrupted="+autoResumeInterrupted+", resumeQueueAfterRestart="+resumeQueueAfterRestart+", preventDuplicates="+preventDuplicates+", duplicateDetection="+duplicateDetection+", newDownloadPosition="+newDownloadPosition+", keepScreenAwake="+keepScreenAwake+", pauseOnBatterySaver="+pauseOnBatterySaver+", pauseOnOverheat="+pauseOnOverheat+", autoRetryOnReconnect="+autoRetryOnReconnect+", speedLimitEnabled="+speedLimitEnabled+", speedLimitKbps="+speedLimitKbps+", scheduleEnabled="+scheduleEnabled+", scheduleStartMinutes="+scheduleStartMinutes+", scheduleEndMinutes="+scheduleEndMinutes+", postDownloadAction="+postDownloadAction+")";}
}
