package com.kira.kdownloader.settings;

import java.util.Objects;

public final class DownloadSettings {
    private final DownloadType downloadType; private final VideoFormat videoFormat; private final AudioFormat audioFormat;
    private final VideoQuality videoQuality; private final AudioQuality audioQuality; private final FrameRatePreference frameRate;
    private final boolean preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload;
    private final boolean downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate;
    public DownloadSettings(){this(DownloadType.VIDEO,VideoFormat.MP4,AudioFormat.MP3,VideoQuality.BEST,AudioQuality.BEST,FrameRatePreference.BEST,false,true,true,false,true,true,true,true);}
    public DownloadSettings(DownloadType downloadType,VideoFormat videoFormat,AudioFormat audioFormat,VideoQuality videoQuality,
                            AudioQuality audioQuality,FrameRatePreference frameRate,boolean preferHdr,
                            boolean preferAndroidCompatibleCodecs,boolean autoFallbackQuality,boolean askQualityBeforeEachDownload,
                            boolean downloadThumbnail,boolean embedThumbnail,boolean embedMetadata,boolean preserveUploadDate){this.downloadType=downloadType;this.videoFormat=videoFormat;this.audioFormat=audioFormat;this.videoQuality=videoQuality;this.audioQuality=audioQuality;this.frameRate=frameRate;this.preferHdr=preferHdr;this.preferAndroidCompatibleCodecs=preferAndroidCompatibleCodecs;this.autoFallbackQuality=autoFallbackQuality;this.askQualityBeforeEachDownload=askQualityBeforeEachDownload;this.downloadThumbnail=downloadThumbnail;this.embedThumbnail=embedThumbnail;this.embedMetadata=embedMetadata;this.preserveUploadDate=preserveUploadDate;}
    public DownloadType getDownloadType(){return downloadType;} public VideoFormat getVideoFormat(){return videoFormat;}
    public AudioFormat getAudioFormat(){return audioFormat;} public VideoQuality getVideoQuality(){return videoQuality;}
    public AudioQuality getAudioQuality(){return audioQuality;} public FrameRatePreference getFrameRate(){return frameRate;}
    public boolean getPreferHdr(){return preferHdr;} public boolean getPreferAndroidCompatibleCodecs(){return preferAndroidCompatibleCodecs;}
    public boolean getAutoFallbackQuality(){return autoFallbackQuality;} public boolean getAskQualityBeforeEachDownload(){return askQualityBeforeEachDownload;}
    public boolean getDownloadThumbnail(){return downloadThumbnail;} public boolean getEmbedThumbnail(){return embedThumbnail;}
    public boolean getEmbedMetadata(){return embedMetadata;} public boolean getPreserveUploadDate(){return preserveUploadDate;}
    public DownloadSettings withDownloadType(DownloadType v){return new DownloadSettings(v,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withVideoFormat(VideoFormat v){return new DownloadSettings(downloadType,v,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withAudioFormat(AudioFormat v){return new DownloadSettings(downloadType,videoFormat,v,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withVideoQuality(VideoQuality v){return new DownloadSettings(downloadType,videoFormat,audioFormat,v,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withAudioQuality(AudioQuality v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,v,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withFrameRate(FrameRatePreference v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,v,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withPreferHdr(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,v,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withPreferAndroidCompatibleCodecs(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,v,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withAutoFallbackQuality(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,v,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withAskQualityBeforeEachDownload(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,v,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withDownloadThumbnail(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,v,embedThumbnail,embedMetadata,preserveUploadDate);}
    public DownloadSettings withEmbedThumbnail(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,v,embedMetadata,preserveUploadDate);}
    public DownloadSettings withEmbedMetadata(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,v,preserveUploadDate);}
    public DownloadSettings withPreserveUploadDate(boolean v){return new DownloadSettings(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,v);}
    @Override public boolean equals(Object o){if(this==o)return true;if(!(o instanceof DownloadSettings))return false;DownloadSettings x=(DownloadSettings)o;return preferHdr==x.preferHdr&&preferAndroidCompatibleCodecs==x.preferAndroidCompatibleCodecs&&autoFallbackQuality==x.autoFallbackQuality&&askQualityBeforeEachDownload==x.askQualityBeforeEachDownload&&downloadThumbnail==x.downloadThumbnail&&embedThumbnail==x.embedThumbnail&&embedMetadata==x.embedMetadata&&preserveUploadDate==x.preserveUploadDate&&downloadType==x.downloadType&&videoFormat==x.videoFormat&&audioFormat==x.audioFormat&&videoQuality==x.videoQuality&&audioQuality==x.audioQuality&&frameRate==x.frameRate;}
    @Override public int hashCode(){return Objects.hash(downloadType,videoFormat,audioFormat,videoQuality,audioQuality,frameRate,preferHdr,preferAndroidCompatibleCodecs,autoFallbackQuality,askQualityBeforeEachDownload,downloadThumbnail,embedThumbnail,embedMetadata,preserveUploadDate);}
    @Override public String toString(){return "DownloadSettings(downloadType="+downloadType+", videoFormat="+videoFormat+", audioFormat="+audioFormat+", videoQuality="+videoQuality+", audioQuality="+audioQuality+", frameRate="+frameRate+", preferHdr="+preferHdr+", preferAndroidCompatibleCodecs="+preferAndroidCompatibleCodecs+", autoFallbackQuality="+autoFallbackQuality+", askQualityBeforeEachDownload="+askQualityBeforeEachDownload+", downloadThumbnail="+downloadThumbnail+", embedThumbnail="+embedThumbnail+", embedMetadata="+embedMetadata+", preserveUploadDate="+preserveUploadDate+")";}
}
