package com.kira.kdownloader.settings;

import androidx.lifecycle.LiveData;
import androidx.lifecycle.MediatorLiveData;

import com.kira.kdownloader.settings.store.InMemorySecureStore;
import com.kira.kdownloader.settings.store.KeyValueStore;
import com.kira.kdownloader.settings.store.SecureStore;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

public final class SettingsRepository {
    private static final String UNSET="\u0000__kdl_unset__";
    private final KeyValueStore store; private final SecureStore secure;
    public interface Transform{AppSettings apply(AppSettings settings);}
    public SettingsRepository(KeyValueStore store){this(store,new InMemorySecureStore());}
    public SettingsRepository(KeyValueStore store,SecureStore secure){this.store=store;this.secure=secure;boolean fresh=!store.contains(SettingsKeys.VERSION);SettingsMigration.migrateIfNeeded(store);if(fresh)store.edit(editor->encodeFields(AppSettings.DEFAULTS,new EditorSink(editor)));}
    public AppSettings read(){AppSettings decoded=decode(new StoreSource(store));return decoded.withNetwork(decoded.getNetwork().withProxyPasswordSet(store.getBoolean(SettingsKeys.NW_PROXY_PASSWORD_SET,false)));}
    public LiveData<AppSettings> observe(){MediatorLiveData<AppSettings> result=new MediatorLiveData<>();result.setValue(read());result.addSource(store.getChanges(),ignored->result.setValue(read()));return result;}
    public void save(AppSettings settings){AppSettings clean=sanitize(settings);store.edit(editor->encodeFields(clean,new DiffEditorSink(editor)));}
    public void update(Transform transform){save(transform.apply(read()));}
    public void setProxyPassword(String password){if(password==null||password.isEmpty()){secure.remove(SecureKeys.PROXY_PASSWORD);store.edit(editor->editor.putBoolean(SettingsKeys.NW_PROXY_PASSWORD_SET,false));}else{secure.put(SecureKeys.PROXY_PASSWORD,password);store.edit(editor->editor.putBoolean(SettingsKeys.NW_PROXY_PASSWORD_SET,true));}}
    public String proxyPassword(){return secure.get(SecureKeys.PROXY_PASSWORD);}
    public void resetCategory(SettingsCategory category){AppSettings defaults=AppSettings.DEFAULTS,current=read(),reset;switch(category){case DOWNLOAD:reset=current.withDownload(defaults.getDownload());break;case STORAGE:reset=current.withStorage(defaults.getStorage());break;case BEHAVIOR:reset=current.withBehavior(defaults.getBehavior());break;case NETWORK:setProxyPassword(null);reset=current.withNetwork(defaults.getNetwork());break;case SUBTITLES:reset=current.withSubtitles(defaults.getSubtitles());break;case NOTIFICATIONS:reset=current.withNotifications(defaults.getNotifications());break;case APPEARANCE:reset=current.withAppearance(defaults.getAppearance());break;case HISTORY:reset=current.withHistory(defaults.getHistory());break;default:reset=current.withProcessing(defaults.getProcessing());}save(reset);}
    public void resetAll(){setProxyPassword(null);save(AppSettings.DEFAULTS);}
    public String exportToJson(){Map<String,String> values=new LinkedHashMap<>();values.put(SettingsKeys.VERSION,Integer.toString(SettingsKeys.CURRENT_VERSION));encodeFields(sanitize(read()),new MapSink(values));return SettingsCodec.encode(values);}

    public abstract static class ImportResult{private ImportResult(){}public static final class Success extends ImportResult{private final int applied;public Success(int applied){this.applied=applied;}public int getApplied(){return applied;}@Override public boolean equals(Object o){return o instanceof Success&&applied==((Success)o).applied;}@Override public int hashCode(){return applied;}@Override public String toString(){return "Success(applied="+applied+")";}}public static final class Failure extends ImportResult{private final String reason;public Failure(String reason){this.reason=reason;}public String getReason(){return reason;}@Override public boolean equals(Object o){return o instanceof Failure&&reason.equals(((Failure)o).reason);}@Override public int hashCode(){return reason.hashCode();}@Override public String toString(){return "Failure(reason="+reason+")";}}}
    public ImportResult importFromJson(String json){Map<String,String> map=SettingsCodec.decode(json);if(map==null)return new ImportResult.Failure("This file is not a valid settings export.");if(map.isEmpty())return new ImportResult.Failure("The settings file is empty.");save(decode(new MapSource(map)));int applied=map.containsKey(SettingsKeys.VERSION)?map.size()-1:map.size();return new ImportResult.Success(applied);}

    private AppSettings sanitize(AppSettings settings){StorageSettings storage=settings.getStorage().withFilenameTemplate(FilenameTemplate.validate(settings.getStorage().getFilenameTemplate()) instanceof FilenameTemplate.Validation.Valid?settings.getStorage().getFilenameTemplate():"{title}").withMaxFilenameLength(clamp(settings.getStorage().getMaxFilenameLength(),FilenameTemplate.MIN_LENGTH,FilenameTemplate.MAX_LENGTH));BehaviorSettings behavior=settings.getBehavior().withMaxSimultaneousDownloads(clamp(settings.getBehavior().getMaxSimultaneousDownloads(),1,5)).withMaxRetryCount(clamp(settings.getBehavior().getMaxRetryCount(),0,10)).withSpeedLimitKbps(Math.max(1,settings.getBehavior().getSpeedLimitKbps())).withScheduleStartMinutes(clamp(settings.getBehavior().getScheduleStartMinutes(),0,1439)).withScheduleEndMinutes(clamp(settings.getBehavior().getScheduleEndMinutes(),0,1439));NetworkSettings network=settings.getNetwork().withProxyPort(clamp(settings.getNetwork().getProxyPort(),0,65535)).withMobileDataWarningMb(Math.max(1,settings.getNetwork().getMobileDataWarningMb()));return settings.withStorage(storage).withBehavior(behavior).withNetwork(network).withProcessing(settings.getProcessing().withMaxTempStorageMb(Math.max(1,settings.getProcessing().getMaxTempStorageMb())));}
    private static int clamp(int value,int min,int max){return Math.max(min,Math.min(max,value));}

    private AppSettings decode(Source s){return new AppSettings(
            new DownloadSettings(s.option(SettingsKeys.DL_TYPE,DownloadType.values(),DownloadType.VIDEO),s.option(SettingsKeys.DL_VIDEO_FORMAT,VideoFormat.values(),VideoFormat.MP4),s.option(SettingsKeys.DL_AUDIO_FORMAT,AudioFormat.values(),AudioFormat.MP3),s.option(SettingsKeys.DL_VIDEO_QUALITY,VideoQuality.values(),VideoQuality.BEST),s.option(SettingsKeys.DL_AUDIO_QUALITY,AudioQuality.values(),AudioQuality.BEST),s.option(SettingsKeys.DL_FRAME_RATE,FrameRatePreference.values(),FrameRatePreference.BEST),s.bool(SettingsKeys.DL_PREFER_HDR,false),s.bool(SettingsKeys.DL_ANDROID_CODECS,true),s.bool(SettingsKeys.DL_AUTO_FALLBACK,true),s.bool(SettingsKeys.DL_ASK_QUALITY,false),s.bool(SettingsKeys.DL_THUMBNAIL,true),s.bool(SettingsKeys.DL_EMBED_THUMBNAIL,true),s.bool(SettingsKeys.DL_EMBED_METADATA,true),s.bool(SettingsKeys.DL_PRESERVE_DATE,true)),
            new StorageSettings(s.str(SettingsKeys.ST_FOLDER,""),s.str(SettingsKeys.ST_VIDEO_FOLDER,""),s.str(SettingsKeys.ST_AUDIO_FOLDER,""),s.str(SettingsKeys.ST_TEMP_FOLDER,""),s.bool(SettingsKeys.ST_WARN_LOW_SPACE,true),s.option(SettingsKeys.ST_CONFLICT,FilenameConflict.values(),FilenameConflict.ADD_NUMBER),s.str(SettingsKeys.ST_TEMPLATE,"{title}"),s.integer(SettingsKeys.ST_MAX_NAME_LEN,120),s.option(SettingsKeys.ST_SUBFOLDER,SubfolderOrganization.values(),SubfolderOrganization.NONE)),
            new BehaviorSettings(s.bool(SettingsKeys.BH_CONFIRM,false),s.integer(SettingsKeys.BH_MAX_PARALLEL,2),s.integer(SettingsKeys.BH_MAX_RETRY,3),s.bool(SettingsKeys.BH_AUTO_RESUME,true),s.bool(SettingsKeys.BH_RESUME_QUEUE,true),s.bool(SettingsKeys.BH_PREVENT_DUP,true),s.option(SettingsKeys.BH_DUP_METHOD,DuplicateDetection.values(),DuplicateDetection.SOURCE_URL),s.option(SettingsKeys.BH_QUEUE_POSITION,QueuePosition.values(),QueuePosition.BOTTOM),s.bool(SettingsKeys.BH_KEEP_AWAKE,false),s.bool(SettingsKeys.BH_PAUSE_BATTERY,true),s.bool(SettingsKeys.BH_PAUSE_HOT,true),s.bool(SettingsKeys.BH_RETRY_RECONNECT,true),s.bool(SettingsKeys.BH_SPEED_LIMIT_ON,false),s.integer(SettingsKeys.BH_SPEED_LIMIT_KBPS,1024),s.bool(SettingsKeys.BH_SCHEDULE_ON,false),s.integer(SettingsKeys.BH_SCHEDULE_START,0),s.integer(SettingsKeys.BH_SCHEDULE_END,360),s.option(SettingsKeys.BH_POST_ACTION,PostDownloadAction.values(),PostDownloadAction.NOTHING)),
            new NetworkSettings(s.option(SettingsKeys.NW_ALLOWED,NetworkType.values(),NetworkType.WIFI_AND_MOBILE),s.bool(SettingsKeys.NW_ROAMING,false),s.bool(SettingsKeys.NW_CONFIRM_MOBILE,true),s.integer(SettingsKeys.NW_WARN_MB,100),s.bool(SettingsKeys.NW_METERED_AS_MOBILE,true),s.bool(SettingsKeys.NW_PAUSE_ON_CHANGE,false),s.bool(SettingsKeys.NW_RETRY_LOSS,true),s.option(SettingsKeys.NW_PROXY_TYPE,ProxyType.values(),ProxyType.DISABLED),s.str(SettingsKeys.NW_PROXY_HOST,""),s.integer(SettingsKeys.NW_PROXY_PORT,0),s.str(SettingsKeys.NW_PROXY_USER,""),false),
            new SubtitleSettings(s.bool(SettingsKeys.SB_ENABLED,false),s.str(SettingsKeys.SB_LANG,"en"),s.str(SettingsKeys.SB_FALLBACK_LANG,""),s.option(SettingsKeys.SB_TYPE,SubtitleTypePreference.values(),SubtitleTypePreference.PREFER_MANUAL),s.option(SettingsKeys.SB_FORMAT,SubtitleFormat.values(),SubtitleFormat.SRT),s.bool(SettingsKeys.SB_EMBED,true),s.bool(SettingsKeys.SB_SEPARATE,false),s.bool(SettingsKeys.SB_ALL_LANGS,false),s.bool(SettingsKeys.SB_LANG_IN_NAME,true)),
            new NotificationSettings(s.bool(SettingsKeys.NT_PROGRESS,true),s.bool(SettingsKeys.NT_EACH_COMPLETE,true),s.bool(SettingsKeys.NT_ALL_COMPLETE,true),s.bool(SettingsKeys.NT_FAILURE,true),s.bool(SettingsKeys.NT_SOUND,false),s.bool(SettingsKeys.NT_VIBRATION,true),s.bool(SettingsKeys.NT_ACTIONS,true),s.bool(SettingsKeys.NT_GROUP,true)),
            new AppearanceSettings(s.option(SettingsKeys.AP_THEME,AppTheme.values(),AppTheme.SYSTEM),s.bool(SettingsKeys.AP_DYNAMIC_COLOR,false),s.str(SettingsKeys.AP_LANGUAGE,""),s.bool(SettingsKeys.AP_COMPACT,false),s.bool(SettingsKeys.AP_SHOW_SIZE,true),s.bool(SettingsKeys.AP_SHOW_SPEED,true),s.bool(SettingsKeys.AP_SHOW_ETA,true),s.bool(SettingsKeys.AP_REDUCE_ANIM,false),s.bool(SettingsKeys.AP_HIGH_CONTRAST,false)),
            new HistorySettings(s.bool(SettingsKeys.HS_KEEP,true),s.option(SettingsKeys.HS_RETENTION,HistoryRetention.values(),HistoryRetention.FOREVER),s.bool(SettingsKeys.HS_RECENT_URLS,true),s.bool(SettingsKeys.HS_SEARCH,true)),
            new ProcessingSettings(s.bool(SettingsKeys.PR_ENABLE,false),s.bool(SettingsKeys.PR_DELETE_SOURCE,false),s.bool(SettingsKeys.PR_PRESERVE_ON_FAIL,true),s.bool(SettingsKeys.PR_HW_ACCEL,true),s.option(SettingsKeys.PR_PRIORITY,ProcessingPriority.values(),ProcessingPriority.BALANCED),s.bool(SettingsKeys.PR_BACKGROUND,true),s.integer(SettingsKeys.PR_MAX_TEMP_MB,2048),s.option(SettingsKeys.PR_LOG_LEVEL,DiagnosticLogLevel.values(),DiagnosticLogLevel.ERRORS)));
    }

    private void encodeFields(AppSettings a,Sink x){DownloadSettings d=a.getDownload();x.str(SettingsKeys.DL_TYPE,d.getDownloadType().getKey());x.str(SettingsKeys.DL_VIDEO_FORMAT,d.getVideoFormat().getKey());x.str(SettingsKeys.DL_AUDIO_FORMAT,d.getAudioFormat().getKey());x.str(SettingsKeys.DL_VIDEO_QUALITY,d.getVideoQuality().getKey());x.str(SettingsKeys.DL_AUDIO_QUALITY,d.getAudioQuality().getKey());x.str(SettingsKeys.DL_FRAME_RATE,d.getFrameRate().getKey());x.bool(SettingsKeys.DL_PREFER_HDR,d.getPreferHdr());x.bool(SettingsKeys.DL_ANDROID_CODECS,d.getPreferAndroidCompatibleCodecs());x.bool(SettingsKeys.DL_AUTO_FALLBACK,d.getAutoFallbackQuality());x.bool(SettingsKeys.DL_ASK_QUALITY,d.getAskQualityBeforeEachDownload());x.bool(SettingsKeys.DL_THUMBNAIL,d.getDownloadThumbnail());x.bool(SettingsKeys.DL_EMBED_THUMBNAIL,d.getEmbedThumbnail());x.bool(SettingsKeys.DL_EMBED_METADATA,d.getEmbedMetadata());x.bool(SettingsKeys.DL_PRESERVE_DATE,d.getPreserveUploadDate());
        StorageSettings st=a.getStorage();x.str(SettingsKeys.ST_FOLDER,st.getDownloadFolderUri());x.str(SettingsKeys.ST_VIDEO_FOLDER,st.getVideoFolderUri());x.str(SettingsKeys.ST_AUDIO_FOLDER,st.getAudioFolderUri());x.str(SettingsKeys.ST_TEMP_FOLDER,st.getTempFolderUri());x.bool(SettingsKeys.ST_WARN_LOW_SPACE,st.getWarnOnLowSpace());x.str(SettingsKeys.ST_CONFLICT,st.getFilenameConflict().getKey());x.str(SettingsKeys.ST_TEMPLATE,st.getFilenameTemplate());x.integer(SettingsKeys.ST_MAX_NAME_LEN,st.getMaxFilenameLength());x.str(SettingsKeys.ST_SUBFOLDER,st.getSubfolderOrganization().getKey());
        BehaviorSettings b=a.getBehavior();x.bool(SettingsKeys.BH_CONFIRM,b.getConfirmBeforeDownload());x.integer(SettingsKeys.BH_MAX_PARALLEL,b.getMaxSimultaneousDownloads());x.integer(SettingsKeys.BH_MAX_RETRY,b.getMaxRetryCount());x.bool(SettingsKeys.BH_AUTO_RESUME,b.getAutoResumeInterrupted());x.bool(SettingsKeys.BH_RESUME_QUEUE,b.getResumeQueueAfterRestart());x.bool(SettingsKeys.BH_PREVENT_DUP,b.getPreventDuplicates());x.str(SettingsKeys.BH_DUP_METHOD,b.getDuplicateDetection().getKey());x.str(SettingsKeys.BH_QUEUE_POSITION,b.getNewDownloadPosition().getKey());x.bool(SettingsKeys.BH_KEEP_AWAKE,b.getKeepScreenAwake());x.bool(SettingsKeys.BH_PAUSE_BATTERY,b.getPauseOnBatterySaver());x.bool(SettingsKeys.BH_PAUSE_HOT,b.getPauseOnOverheat());x.bool(SettingsKeys.BH_RETRY_RECONNECT,b.getAutoRetryOnReconnect());x.bool(SettingsKeys.BH_SPEED_LIMIT_ON,b.getSpeedLimitEnabled());x.integer(SettingsKeys.BH_SPEED_LIMIT_KBPS,b.getSpeedLimitKbps());x.bool(SettingsKeys.BH_SCHEDULE_ON,b.getScheduleEnabled());x.integer(SettingsKeys.BH_SCHEDULE_START,b.getScheduleStartMinutes());x.integer(SettingsKeys.BH_SCHEDULE_END,b.getScheduleEndMinutes());x.str(SettingsKeys.BH_POST_ACTION,b.getPostDownloadAction().getKey());
        NetworkSettings n=a.getNetwork();x.str(SettingsKeys.NW_ALLOWED,n.getAllowedNetworks().getKey());x.bool(SettingsKeys.NW_ROAMING,n.getAllowRoaming());x.bool(SettingsKeys.NW_CONFIRM_MOBILE,n.getConfirmMobileData());x.integer(SettingsKeys.NW_WARN_MB,n.getMobileDataWarningMb());x.bool(SettingsKeys.NW_METERED_AS_MOBILE,n.getTreatMeteredWifiAsMobile());x.bool(SettingsKeys.NW_PAUSE_ON_CHANGE,n.getPauseOnNetworkChange());x.bool(SettingsKeys.NW_RETRY_LOSS,n.getRetryAfterConnectionLoss());x.str(SettingsKeys.NW_PROXY_TYPE,n.getProxyType().getKey());x.str(SettingsKeys.NW_PROXY_HOST,n.getProxyHost());x.integer(SettingsKeys.NW_PROXY_PORT,n.getProxyPort());x.str(SettingsKeys.NW_PROXY_USER,n.getProxyUsername());
        SubtitleSettings sb=a.getSubtitles();x.bool(SettingsKeys.SB_ENABLED,sb.getDownloadSubtitles());x.str(SettingsKeys.SB_LANG,sb.getPreferredLanguage());x.str(SettingsKeys.SB_FALLBACK_LANG,sb.getFallbackLanguage());x.str(SettingsKeys.SB_TYPE,sb.getSubtitleType().getKey());x.str(SettingsKeys.SB_FORMAT,sb.getFormat().getKey());x.bool(SettingsKeys.SB_EMBED,sb.getEmbedInVideo());x.bool(SettingsKeys.SB_SEPARATE,sb.getSaveAsSeparateFiles());x.bool(SettingsKeys.SB_ALL_LANGS,sb.getIncludeAllLanguages());x.bool(SettingsKeys.SB_LANG_IN_NAME,sb.getAddLanguageCodeToFilename());
        NotificationSettings nt=a.getNotifications();x.bool(SettingsKeys.NT_PROGRESS,nt.getShowProgress());x.bool(SettingsKeys.NT_EACH_COMPLETE,nt.getNotifyOnEachComplete());x.bool(SettingsKeys.NT_ALL_COMPLETE,nt.getNotifyOnAllComplete());x.bool(SettingsKeys.NT_FAILURE,nt.getNotifyOnFailure());x.bool(SettingsKeys.NT_SOUND,nt.getSound());x.bool(SettingsKeys.NT_VIBRATION,nt.getVibration());x.bool(SettingsKeys.NT_ACTIONS,nt.getShowActions());x.bool(SettingsKeys.NT_GROUP,nt.getGroupNotifications());
        AppearanceSettings ap=a.getAppearance();x.str(SettingsKeys.AP_THEME,ap.getTheme().getKey());x.bool(SettingsKeys.AP_DYNAMIC_COLOR,ap.getDynamicColor());x.str(SettingsKeys.AP_LANGUAGE,ap.getLanguageTag());x.bool(SettingsKeys.AP_COMPACT,ap.getCompactList());x.bool(SettingsKeys.AP_SHOW_SIZE,ap.getShowFileSize());x.bool(SettingsKeys.AP_SHOW_SPEED,ap.getShowSpeed());x.bool(SettingsKeys.AP_SHOW_ETA,ap.getShowEta());x.bool(SettingsKeys.AP_REDUCE_ANIM,ap.getReduceAnimations());x.bool(SettingsKeys.AP_HIGH_CONTRAST,ap.getHighContrast());
        HistorySettings h=a.getHistory();x.bool(SettingsKeys.HS_KEEP,h.getKeepHistory());x.str(SettingsKeys.HS_RETENTION,h.getRetention().getKey());x.bool(SettingsKeys.HS_RECENT_URLS,h.getSaveRecentUrls());x.bool(SettingsKeys.HS_SEARCH,h.getSaveSearchHistory());
        ProcessingSettings p=a.getProcessing();x.bool(SettingsKeys.PR_ENABLE,p.getEnableConversion());x.bool(SettingsKeys.PR_DELETE_SOURCE,p.getDeleteSourceAfterConversion());x.bool(SettingsKeys.PR_PRESERVE_ON_FAIL,p.getPreserveSourceOnFailure());x.bool(SettingsKeys.PR_HW_ACCEL,p.getPreferHardwareAcceleration());x.str(SettingsKeys.PR_PRIORITY,p.getPriority().getKey());x.bool(SettingsKeys.PR_BACKGROUND,p.getAllowBackgroundProcessing());x.integer(SettingsKeys.PR_MAX_TEMP_MB,p.getMaxTempStorageMb());x.str(SettingsKeys.PR_LOG_LEVEL,p.getLogLevel().getKey());}

    private interface Source{String str(String key,String fallback);int integer(String key,int fallback);boolean bool(String key,boolean fallback);default <T extends Enum<T>&SettingOption>T option(String key,T[] values,T fallback){return SettingsOptions.optionFromKey(values,str(key,fallback.getKey()),fallback);}}
    private static final class StoreSource implements Source{private final KeyValueStore store;StoreSource(KeyValueStore store){this.store=store;}public String str(String k,String d){return store.getString(k,d);}public int integer(String k,int d){return store.getInt(k,d);}public boolean bool(String k,boolean d){return store.getBoolean(k,d);}}
    private static final class MapSource implements Source{private final Map<String,String> map;MapSource(Map<String,String> map){this.map=map;}public String str(String k,String d){String v=map.get(k);return v==null?d:v;}public int integer(String k,int d){try{return Integer.parseInt(str(k,Integer.toString(d)));}catch(NumberFormatException e){return d;}}public boolean bool(String k,boolean d){String v=map.get(k);if("true".equals(v))return true;if("false".equals(v))return false;return d;}}
    private interface Sink{void str(String key,String value);void integer(String key,int value);void bool(String key,boolean value);}
    private static final class EditorSink implements Sink{private final KeyValueStore.Editor e;EditorSink(KeyValueStore.Editor e){this.e=e;}public void str(String k,String v){e.putString(k,v);}public void integer(String k,int v){e.putInt(k,v);}public void bool(String k,boolean v){e.putBoolean(k,v);}}
    private final class DiffEditorSink implements Sink{private final KeyValueStore.Editor e;DiffEditorSink(KeyValueStore.Editor e){this.e=e;}public void str(String k,String v){if(!store.getString(k,UNSET).equals(v))e.putString(k,v);}public void integer(String k,int v){if(store.getInt(k,Integer.MIN_VALUE)!=v)e.putInt(k,v);}public void bool(String k,boolean v){if(store.getBoolean(k,!v)!=v)e.putBoolean(k,v);}}
    private static final class MapSink implements Sink{private final Map<String,String> map;MapSink(Map<String,String> map){this.map=map;}public void str(String k,String v){map.put(k,v);}public void integer(String k,int v){map.put(k,Integer.toString(v));}public void bool(String k,boolean v){map.put(k,Boolean.toString(v));}}
}
